### PR TITLE
Add the latest video renders

### PR DESCRIPTION
**Pull request by dzole0311**
Adding the latest video renders.

### CODE REVIEW

**Review by j08lue — APPROVED** [review]
Content changes seem right. Performed a simple consistency check: Paused video playback and selected year 2100. Switching through scenarios from low to high shows progressively warmer temperatures. ✅

**Comment by j08lue** [comment]
Hmm, wait a sed - differences between High and Very high even at year 2100 are not noticeable. Is that as expected?

**Comment by dzole0311** [comment]
@j08lue afaik, there are diffs, probably more noticeable if you compare the videos manually side by side, at year 2100 🤔

**Comment by j08lue** [comment]
Ah, good idea to open the app in two tabs and switch rapidly. 💡 

Nope, I can confirm that The 370 and 585 videos are indeed 100% identical, also at other time steps, say 2050.

We need to check this with @agurvich.

**Comment by dzole0311** [comment]
@j08lue It's my bad, I made a mistake. Will fix.

**Pull request merged**
