### PR TITLE
Adding Digital Analytics Program (DAP) header to the app

### PR DESCRIPTION
**Pull request by amarouane-ABDELHAK**
Adding Digital Analytics Program (DAP) header to the app but only if deployed to .gov domains (staging and production GitHub environments)

### CODE REVIEW

**Review by j08lue — COMMENTED** [review]
I am unable to find the extra line before `</head>` this script should add in the deploy preview. But I guess that is because the environment variable is only added in the `deploy` workflow, right?

Certainly looks clean.

**Comment by dzole0311** [comment]
Thanks @amarouane-ABDELHAK, looks good! I made a small adjustment to the Vite config and I've also added the `ADD_DAP_SCRIPT` variable to the Netlify deployment settings, so the DAP script should now appear in the deploy previews as well. We can also set it to false for the Netlify previews if we see its adding noise to the DAP analytics.

**Review by dzole0311 — APPROVED** [review]

**Comment by amarouane-ABDELHAK** [comment]
I had the impression that we only need DAP script on a public facing  government websites (.gov domains) we will not need to put them for the netlify previews)
https://github.com/NASA-IMPACT/EIC-Mobile/issues/38#issuecomment-2417667026

**Review by freitagb — APPROVED** [review]
looks good to me. Thanks!

**Comment by dzole0311** [comment]
> I had the impression that we only need DAP script on a public facing government websites (.gov domains) we will not need to put them for the netlify previews)

Okay, I removed the variable from the Netlify settings (I missed the original comment in the other issue).

**Pull request merged**
